spring:
  application:
    name: Service films
  datasource:
    username: sa
    password:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  security:
    enabled: false
