spring:
  application:
    name: Service films
  datasource:
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: true
  endpoints:
    web:
      expose: '*'
